# Generated by Django 4.0.1 on 2022-01-28 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='content_dec',
            field=models.CharField(default='.....', max_length=245),
        ),
    ]
